# Site settings
title: Anxhelo Lushka
description: My personal website and blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lushka.al" # the base hostname & protocol for your site
locale: en-US

# User settings
username: Anxhelo Lushka
user_description: Graphic Designer/Frontend Developer
user_title: Designer & Developer
email: anxhelo@lushka.al
github_username:  AnXh3L0
twitter_username:  anxhelolushka
instagram_username:  anxhelolushka
telegram_username: AnXh3L0
cloud: cloud.lushka.al
git: git.lushka.al

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

paginate: 6

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Portfolio
    url: /portfolio
  - title: Categories
    url: /categories
  - title: Tags
    url: /tags
  - title: About Me
    url: /about
  - title: Start Page
    url: /start
  - title: Web Filters
    url: /blocklist
  - title: Feed
    url: /feed.xml

plugins:
  - jekyll-paginate

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
