# Site settings
title: Anxhelo Lushka
description: My personal website and blog
baseurl: "https://anxh3l0.github.io/lushka.al" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Anxhelo Lushka
user_description: Graphic and frontend designer
user_title: Designer
email: anxhelo@lushka.al
github_username:  AnXh3L0
telegram_username: AnXh3L0
instagram_username: angelolushka


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /lushka.al
  - title: Series
    url: /lushka.al/series
  - title: Tags
    url: /lushka.al/tags
  - title: About Me
    url: /lushka.al/about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
